[versions]

micronaut = "4.6.1"
micronaut-test = "4.5.0"
groovy = "4.0.13"
spock = "2.3-groovy-4.0"
micronaut-logging = "1.0.0"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
