[versions]

micronaut = "4.0.0-M2"
micronaut-test = "4.0.0-M1"
groovy = "4.0.11"
spock = "2.3-groovy-4.0"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
