[versions]

micronaut = "4.0.0-RC5"
micronaut-test = "4.0.0-M9"
groovy = "4.0.12"
spock = "2.3-groovy-4.0"
micronaut-logging = "1.0.0-M5"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
